---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.15


inputs:
- name: pcf-pipelines

params:
  PRODUCT_NAME:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  ERRANDS_TO_DISABLE:

run:
  path: /bin/sh
  args:
  - -c
  - |
    chmod +x pcf-pipelines/tasks/disable-errands/task.sh
    ./pcf-pipelines/tasks/disable-errands/task.sh
